# 소수판별 is_prime()
[2,3,4,5,6,7,8,9] -> [true, true, false, true, false, true, false, false]

In [8]:
def is_prime(n):
    result = []

    for x in n:                 # x가 리스트 안의 숫자 하나
        if x < 2:
            result.append(False)
            continue

        isPrime = True
        for d in range(2, x):   # 2부터 x-1까지
            if x % d == 0:
                isPrime = False
                break

        result.append(isPrime)

    return result

print(is_prime([2,3,4,5,6,7,8,9]))
# [True, True, False, True, False, True, False, False]



[True, True, False, True, False, True, False, False]


# 등수 구하기 - 평균점수(영어점수, 수학점수)

In [17]:
score1=[[80,70],[90,50],[40,70],[50,80]]

avgs=[]
for scores in score1:
    avgs.append(sum(scores)/len(scores))

ranks=[]
for a in avgs:
    rank = 0
    for b in avgs:
        if b>a:
            rank+=1
            ranks.append(rank)

for i in range(len(score1)):
    print(f"{i+1}번: 점수={score1[i]}, 평균={avgs[i]:.2f}, 등수={ranks[i]}")
# rank(score1) # [1,2,4,3]

1번: 점수=[80, 70], 평균=75.00, 등수=1
2번: 점수=[90, 50], 평균=70.00, 등수=1
3번: 점수=[40, 70], 평균=55.00, 등수=2
4번: 점수=[50, 80], 평균=65.00, 등수=3


In [22]:
import random as r

r.randint(1,100)

58

#### 사용자 정의 모듈

In [23]:
import mymodule as mm

print(mm.my_add(11,5))
print(mm.my_sub(11,5))

10
4
16
6


In [26]:
import numpy as np
import time
 
size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)
 
start_time = time.time()
result_list = [x * 2 for x in py_list]
end_time = time.time()
print(f'Python 리스트 연산: {end_time - start_time:.5f}초')
 
start_time = time.time()
result_array = np_array * 2
end_time = time.time()
print(f'Numpy 배열 연산: {end_time - start_time:.5f}초')

Python 리스트 연산: 0.07671초
Numpy 배열 연산: 0.00400초


In [27]:
arr=[1,2,3,4,5]
brr=[6,7,8,9,10]

In [28]:
alist=np.array([1,2,3,4,5])
blist=np.array([6,7,8,9,10])

In [29]:
alist+blist

array([ 7,  9, 11, 13, 15])

In [30]:
alist*blist

array([ 6, 14, 24, 36, 50])

In [35]:
data=[0,1,2,3,4,5,6,7,8,9]

# answer=[]
# for i in data:
#     answer.append(i*2)
# answer
datalist=np.array(data)
datalist*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [37]:
alist==2

array([False,  True, False, False, False])

In [40]:
a=np.array([[0,1,2],[3,4,5]])
print(a[0,0], a[0,1], a[1,2])

0 1 5


In [42]:
a=np.array([[0,1,2,3],[4,5,6,7]])
print(a[0, 0:3])

[0 1 2]


In [52]:
a=np.array([[0,1,2,3],[4,5,6,7]])
print(a[:,:2])

[[0 1]
 [4 5]]


In [56]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
# result=[]
# for i in a:
#     if i%2==0:
#         result.append(i)
# print(result)
result=a[a%2==0]
print(result)

[0 2 4 6 8]


In [58]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])

a[idx]

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [60]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
idx=np.array([0, 3])
a[:,idx]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])